-- Prints the full description of the table first_table
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HBTN_0C_0' AND TABLE_NAME = 'FIRST_TABLE';
